export const COMPANY_NAMES: Record<string, string> = {
  MSFT: "Microsoft",
  JNJ: "Johnson & Johnson",
  JPM: "JPMorgan Chase",
  NVDA: "NVIDIA",
  AMZN: "Amazon",
  AAPL: "Apple",
  V: "Visa",
  TSLA: "Tesla",
  UNH: "UnitedHealth Group",
  HD: "Home Depot",
  PG: "Procter & Gamble",
  MA: "Mastercard",
  DIS: "Disney",
  BAC: "Bank of America",
  VZ: "Verizon",
  NFLX: "Netflix",
  PFE: "Pfizer",
  KO: "Coca-Cola",
  CSCO: "Cisco Systems",    
}